name = "vvtv-control-worker"
main = "src/index.ts"
compatibility_date = "2026-02-27"
account_id = "1f43a14fe5bb62b97e7262c5b6b7c476"

routes = [
  { pattern = "api.voulezvous.tv/*", zone_name = "voulezvous.tv" },
  { pattern = "voulezvous.tv/vvtv/*", zone_name = "voulezvous.tv" }
]

[[d1_databases]]
binding = "DB"
database_name = "vvtv-control"
database_id = "9d7f7ad5-cb68-462d-92f4-33ebbb1d9314"
