[package]
name = "vvtv-stream"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
vvtv-types = { path = "../vvtv-types" }

[lints]
workspace = true
