[package]
name = "vvtv-audit"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
parking_lot.workspace = true
vvtv-types = { path = "../vvtv-types" }

[lints]
workspace = true
