[package]
name = "vvtv-queue"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
uuid.workspace = true
vvtv-types = { path = "../vvtv-types" }

[lints]
workspace = true
