[package]
name = "vvtv-curator"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
uuid.workspace = true
vvtv-types = { path = "../vvtv-types" }

[lints]
workspace = true
